### ISSUE TITLE
Trained entity + relation embeddings

### ISSUE THREAD

**Issue by tsafavi** [facebookresearch/ssl-relation-prediction#10]
Hi, thanks for your great contribution with this work :-) Do you plan to make the trained entity + relation embeddings for your SOTA models available for download? 

Tara

**Comment by yihong-chen** [comment]
Thanks for your interest, Tara. This sounds like a good idea! I expect some time before we release the embeddings for all datasets. For now, are there any datasets you prioritise more? I can work on them and generate the embeddings first.

**Comment by tsafavi** [comment]
Great! The datasets I'm most interested in are FB15K-237, WN18RR, CoDEx-M, and CoDEx-S, in that order. Thanks again :)

**Comment by yihong-chen** [comment]
Hey Tara, we have released the ComplEx embeddings for FB15K-237, WN18RR, CoDEx-M, and CoDEx-S. You can download them from the following links
- [FB15K-237](https://dl.fbaipublicfiles.com/ssl-relation-prediction/complex/fb15k237.zip)
- [WN18RR](https://dl.fbaipublicfiles.com/ssl-relation-prediction/complex/wn18rr.zip)
- [CoDEx-M](https://dl.fbaipublicfiles.com/ssl-relation-prediction/complex/codex-m.zip)
- [CoDEx-S](https://dl.fbaipublicfiles.com/ssl-relation-prediction/complex/codex-s.zip)

For CoDEx-L, ogbl-biokg and ogbl-wikikgv2, we expect to release the embeddings in the next few days. Let me know if you have any questions regarding the embeddings.

**Comment by tsafavi** [comment]
Amazing, thanks for your fast response @yihong-chen! I'll open a separate issue if I have any further questions.
