### ISSUE TITLE
Quick check with the new evaluation code

### ISSUE THREAD

**Issue by weihua916** [facebookresearch/ssl-relation-prediction#17]
Hi! This is OGB Team.

We recently released https://github.com/snap-stanford/ogb/releases/tag/1.3.4 which improves the MRR calculation. This should not change your result if your model makes different predictive scores for different triplets, but would penalize those models that give the same predictive scores for different triplets (which is not ideal for link prediction).

Could you update your ogb package to 1.3.4 and run your model again just to confirm everything stays the same (the dataset stays the same. only evaluator changed)? Just one seed should be enough. Thanks!

**Comment by yihong-chen** [comment]
@weihua916 Thanks for the notice. I have rerun the experiments on `ogbl-biokg` and `ogbl-wikikg` with one seed. The results stay the same with ogb 1.3.4.

**Comment by weihua916** [comment]
That's good to confirm. Thank you!
