### ISSUE TITLE
OGB model documentation

### ISSUE THREAD

**Issue by Percefoni** [facebookresearch/ssl-relation-prediction#18]
Good evening. I have a question , regarding your code for the ogb wikidata. I've been working on graph neural networks lately, but because it's something new to me I'm having difficulties. Could I find somewhere documentation for the code and more specifically for the methods.Thanks in advance.

**Comment by yihong-chen** [comment]
Hi @Percefoni thanks for reaching out. This repo was only developed for reproducing our paper https://arxiv.org/abs/2110.02834.  The main focus is on embedding-based methods here, such as ComplEx, TransE, CP, TuckER and RESCAL. We do not have a plan to incorporate GNNs in this repo. If you want to discuss any GNN-related issues, feel free to drop me an email.
