### ISSUE TITLE
ogbl-biokg

### ISSUE THREAD

**Issue by ninjaX2o** [facebookresearch/ssl-relation-prediction#20]
Hi!thanks for your great work, I use your code to prepare dataset ogbl-biokg recently, i found the size of the test.pickle file and valid.pickle file are both 1.2GB,but train.pickle is 181MB, i'm not familiar with this dataset,so I don't know if it's normal

**Comment by yihong-chen** [comment]
@wxxw-blip Hi, it is normal. The valid/test files are bigger as they come with the negative heads/tails to be evaluated on. The associated line of code is [here](https://github.com/facebookresearch/ssl-relation-prediction/blob/a050286473933b6b7b743db43db3529bd305359a/src/preprocess_datasets.py#L122).

**Comment by yihong-chen** [comment]
@wxxw-blip I will close this issue for now. Feel free to open a new one if you have any other question.
